/**
 * Canonical laboratory unit aliases.  The key is a deliberately lossy lookup
 * representation produced by `toUnitLookupKey`; values are never exposed as
 * lookup keys, only as their display-safe canonical unit strings.
 */
export const UNIT_ALIAS_TABLE = Object.freeze({
  'mg/dl': 'mg/dL',
  'mg%': 'mg/dL',
  'ug/l': 'µg/L',
  'mcg/l': 'µg/L',
  'umol/l': 'µmol/L',
  'mmol/l': 'mmol/L',
  mmol: 'mmol/L',
  'meq/l': 'mEq/L',
  'u/l': 'U/L',
  'u/ml': 'U/mL',
  'iu/l': 'IU/L',
  'iu/dl': 'IU/dL',
  'iu/ml': 'IU/mL',
  'miu/l': 'mIU/L',
  'miu/ml': 'mIU/mL',
  'uiu/ml': 'µIU/mL',
  'kiu/l': 'kIU/L',
  'ku/l': 'kU/L',
  'pg/ml': 'pg/mL',
  'ng/ml': 'ng/mL',
  'ng/dl': 'ng/dL',
  'pmol/l': 'pmol/L',
  'nmol/l': 'nmol/L',
  'g/dl': 'g/dL',
  'g/l': 'g/L',
  'mg/l': 'mg/L',
  'mg/24h': 'mg/24h',
  'mg/g': 'mg/g',
  'mg/mmol': 'mg/mmol',
  'mm/hr': 'mm/hr',
  'ug/dl': 'µg/dL',
  'ug/mlfeu': 'µg/mL FEU',
  'ng/l': 'ng/L',
  'mmol/mol': 'mmol/mol',
  'umol/molheme': 'µmol/mol heme',
  'ml/min/1.73m2': 'mL/min/1.73m²',
  'ml/min': 'mL/min',
  'mosm/kg': 'mOsm/kg',
  'nmol/mol': 'nmol/mol',
  'l/l': 'L/L',
  'rbc/hpf': 'RBC/HPF',
  'bacteria/hpf': 'bacteria/HPF',
  'casts/lpf': 'casts/LPF',
  'cells/hpf': 'cells/HPF',
  'cells/ul': 'cells/µL',
  'crystals/hpf': 'crystals/HPF',
  index: 'index',
  ph: 'pH',
  seconds: 'seconds',
  titer: 'titer',
  ratio: 'ratio',
  percent: '%',
  '%': '%',
  fl: 'fL',
  pg: 'pg',
  '10^3/ul': '10^3/µL',
  '10^6/ul': '10^6/µL',
  '10^9/l': '10^9/L',
  '10^12/l': '10^12/L',
});

export default UNIT_ALIAS_TABLE;
